package late.kbase.entity;

public class KbaseKnowledgeTagEntity extends BaseEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_knowledge_tag.k_id
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	private String kId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_knowledge_tag.k_tag
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	private String kTag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_knowledge_tag.k_id
	 *
	 * @return the value of kbase_knowledge_tag.k_id
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	public String getkId() {
		return kId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_knowledge_tag.k_id
	 *
	 * @param kId
	 *            the value for kbase_knowledge_tag.k_id
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	public void setkId(String kId) {
		this.kId = kId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_knowledge_tag.k_tag
	 *
	 * @return the value of kbase_knowledge_tag.k_tag
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	public String getkTag() {
		return kTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_knowledge_tag.k_tag
	 *
	 * @param kTag
	 *            the value for kbase_knowledge_tag.k_tag
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	public void setkTag(String kTag) {
		this.kTag = kTag;
	}
}