package late.kbase.entity;

public class KbaseErrDefEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kbase_err_def.err_code
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kbase_err_def.err_msg
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    private String errMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kbase_err_def.err_lvl
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    private String errLvl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kbase_err_def.err_code
     *
     * @return the value of kbase_err_def.err_code
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kbase_err_def.err_code
     *
     * @param errCode the value for kbase_err_def.err_code
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kbase_err_def.err_msg
     *
     * @return the value of kbase_err_def.err_msg
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kbase_err_def.err_msg
     *
     * @param errMsg the value for kbase_err_def.err_msg
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kbase_err_def.err_lvl
     *
     * @return the value of kbase_err_def.err_lvl
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public String getErrLvl() {
        return errLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kbase_err_def.err_lvl
     *
     * @param errLvl the value for kbase_err_def.err_lvl
     *
     * @mbg.generated Mon Dec 25 21:57:36 CST 2017
     */
    public void setErrLvl(String errLvl) {
        this.errLvl = errLvl;
    }
}