package late.kbase.entity;

import java.util.Date;

public class KbaseUserTicketEntity extends BaseEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_user_ticket.ticket
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	private String ticket;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_user_ticket.user_id
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	private Long userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_user_ticket.last_log_time
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	private Date lastLogTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_user_ticket.ticket
	 *
	 * @return the value of kbase_user_ticket.ticket
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public String getTicket() {
		return ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_user_ticket.ticket
	 *
	 * @param ticket
	 *            the value for kbase_user_ticket.ticket
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_user_ticket.user_id
	 *
	 * @return the value of kbase_user_ticket.user_id
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_user_ticket.user_id
	 *
	 * @param userId
	 *            the value for kbase_user_ticket.user_id
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_user_ticket.last_log_time
	 *
	 * @return the value of kbase_user_ticket.last_log_time
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public Date getLastLogTime() {
		return lastLogTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_user_ticket.last_log_time
	 *
	 * @param lastLogTime
	 *            the value for kbase_user_ticket.last_log_time
	 *
	 * @mbg.generated Mon Jan 15 11:50:18 CST 2018
	 */
	public void setLastLogTime(Date lastLogTime) {
		this.lastLogTime = lastLogTime;
	}
}