package late.kbase.entity;

public class KbaseMenuMastEntity extends BaseEntity{
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_menu_mast.menu_id
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	private String menuId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_menu_mast.menu_desc
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	private String menuDesc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_menu_mast.menu_type
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	private String menuType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_menu_mast.menu_owner
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	private String menuOwner;

	/**
	 * ¸¸½Úµã±àºÅ
	 */
	private String parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kbase_menu_mast.status
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_menu_mast.menu_id
	 *
	 * @return the value of kbase_menu_mast.menu_id
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_menu_mast.menu_id
	 *
	 * @param menuId
	 *            the value for kbase_menu_mast.menu_id
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_menu_mast.menu_desc
	 *
	 * @return the value of kbase_menu_mast.menu_desc
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public String getMenuDesc() {
		return menuDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_menu_mast.menu_desc
	 *
	 * @param menuDesc
	 *            the value for kbase_menu_mast.menu_desc
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_menu_mast.menu_type
	 *
	 * @return the value of kbase_menu_mast.menu_type
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public String getMenuType() {
		return menuType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_menu_mast.menu_type
	 *
	 * @param menuType
	 *            the value for kbase_menu_mast.menu_type
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_menu_mast.menu_owner
	 *
	 * @return the value of kbase_menu_mast.menu_owner
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public String getMenuOwner() {
		return menuOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_menu_mast.menu_owner
	 *
	 * @param menuOwner
	 *            the value for kbase_menu_mast.menu_owner
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public void setMenuOwner(String menuOwner) {
		this.menuOwner = menuOwner;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column kbase_menu_mast.status
	 *
	 * @return the value of kbase_menu_mast.status
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column kbase_menu_mast.status
	 *
	 * @param status
	 *            the value for kbase_menu_mast.status
	 *
	 * @mbg.generated Thu Dec 14 10:32:38 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}