package late.kbase.entity;

/**
 * 用户表实体类
 * 
 * @projectName kbase
 * @packageName late.kbase.entity
 * @fileName UserProfile.java
 * @author chijingjia
 * @createTime :2017年12月4日 下午1:47:11
 * @version: v1.0
 */
public class UserProfileEntity {
	/**
	 * 用户编号
	 */
	private Long userId;
	/**
	 * 用户名
	 */
	private String userName;
	/**
	 * 密码
	 */
	private String password;
	/**
	 * 真实姓名
	 */
	private String realName;
	/**
	 * 级别
	 */
	private String lvl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_profile.USER_ID
	 *
	 * @return the value of user_profile.USER_ID
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_profile.USER_ID
	 *
	 * @param userId
	 *            the value for user_profile.USER_ID
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_profile.USER_NAME
	 *
	 * @return the value of user_profile.USER_NAME
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_profile.USER_NAME
	 *
	 * @param userName
	 *            the value for user_profile.USER_NAME
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_profile.PASSWORD
	 *
	 * @return the value of user_profile.PASSWORD
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_profile.PASSWORD
	 *
	 * @param password
	 *            the value for user_profile.PASSWORD
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_profile.REAL_NAME
	 *
	 * @return the value of user_profile.REAL_NAME
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_profile.REAL_NAME
	 *
	 * @param realName
	 *            the value for user_profile.REAL_NAME
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_profile.LVL
	 *
	 * @return the value of user_profile.LVL
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public String getLvl() {
		return lvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_profile.LVL
	 *
	 * @param lvl
	 *            the value for user_profile.LVL
	 *
	 * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	 */
	public void setLvl(String lvl) {
		this.lvl = lvl;
	}
}