package late.kbase.dao;

import java.util.List;
import java.util.Map;

import late.kbase.entity.KbaseErrDefEntity;

public interface IKbaseErrDefMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_err_def
	 *
	 * @mbg.generated Mon Dec 25 21:57:36 CST 2017
	 */
	int insert(KbaseErrDefEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_err_def
	 *
	 * @mbg.generated Mon Dec 25 21:57:36 CST 2017
	 */
	int insertSelective(KbaseErrDefEntity record);

	/**
	 * 获取所有记录
	 * 
	 * @methodName getAll
	 * @author chijingjia
	 * @createTime 2017年12月25日 下午10:04:39
	 * @version v1.0
	 * @return
	 */
	List<Map<String, String>> getAll();
}