package late.kbase.dao;

import late.kbase.entity.KbaseKnowledgeTagEntity;

public interface IKbaseKnowledgeTagMapper extends BaseMapper<KbaseKnowledgeTagEntity, String> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_knowledge_tag
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	void insert(KbaseKnowledgeTagEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_knowledge_tag
	 *
	 * @mbg.generated Tue Jan 16 09:11:07 CST 2018
	 */
	int insertSelective(KbaseKnowledgeTagEntity record);
}