package late.kbase.dao;

import late.kbase.entity.KbaseMenuMastEntity;

public interface IKbaseMenuMastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kbase_menu_mast
     *
     * @mbg.generated Thu Dec 14 10:32:38 CST 2017
     */
    int insert(KbaseMenuMastEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kbase_menu_mast
     *
     * @mbg.generated Thu Dec 14 10:32:38 CST 2017
     */
    int insertSelective(KbaseMenuMastEntity record);
}