package late.kbase.dao;

import late.kbase.entity.KbaseKnowledgeDetlEntity;

public interface IKbaseKnowledgeDetlMapper extends BaseMapper<KbaseKnowledgeDetlEntity,String> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table kbase_knowledge_dtls
	 * @mbg.generated  Mon Jan 15 18:05:33 CST 2018
	 */
	void insert(KbaseKnowledgeDetlEntity record);

}