package late.kbase.dao;

import late.kbase.entity.KbaseKnowledgeMastEntity;

public interface IKbaseKnowledgeMastMapper extends BaseMapper<KbaseKnowledgeMastEntity, String> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_knowledge_mast
	 *
	 * @mbg.generated Tue Jan 16 09:06:45 CST 2018
	 */
	void insert(KbaseKnowledgeMastEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table kbase_knowledge_mast
	 *
	 * @mbg.generated Tue Jan 16 09:06:45 CST 2018
	 */
	int insertSelective(KbaseKnowledgeMastEntity record);
}