package late.kbase.dao;

import late.kbase.entity.UserProfileEntity;

public interface IUserProfileMapper extends BaseMapper<UserProfileEntity, Long> {

	// /**
	// * This method was generated by MyBatis Generator. This method corresponds
	// * to the database table user_profile
	// *
	// * @mbg.generated Mon Dec 04 13:44:33 CST 2017
	// */
	// int insert(UserProfileEntity record);

	/**
	 * 根据用户名获取用户信息
	 * 
	 * @methodName getByUsername
	 * @author chijingjia
	 * @createTime 2017年12月25日 下午10:32:38
	 * @version v1.0
	 * @param user
	 * @return
	 */
	UserProfileEntity getByUsername(UserProfileEntity user);

}